version: '2'
services:
  wordpress:
    image: wordpress:4.7.0-php7.0-apache
    links:
      - mysql:mysql
    env_file:
      - ./env/wordpress.env
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ../web:/var/www/html
  mysql:
    image: mysql:5
    env_file:
      - ./env/mysql.env
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db:/var/lib/mysql
